"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, MapPin, Mail, Copy, Check, Menu, X, FileText, Layers, PackageSearch, ClipboardList, Workflow } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { profile, projects, type Project } from './profile';

const navigation = [['Work','work'],['Experience','experience'],['Skills','skills'],['About','about'],['Contact','contact']];
function Tags({items}:{items:string[]}){return <ul className="tags" aria-label="Tools and skills">{items.map(item=><li key={item}>{item}</li>)}</ul>}
function ProjectLinks({project}:{project:Project}){const links=[['GitHub',project.repositoryUrl],['Live Dashboard',project.liveUrl],['Download Project',project.downloadUrl]];return <div className="project-links">{links.filter(([,url])=>url).map(([label,url])=><a className="text-link" key={label} href={url!} {...(label==='Download Project'?{download:true}:{target:'_blank',rel:'noopener noreferrer'})}>{label}<ArrowUpRight size={15}/></a>)}</div>}
function CaseStudy({project}:{project:Project}){
 const [open,setOpen]=useState('');
 useEffect(()=>{const sync=()=>setOpen(window.location.hash==='#case-'+project.id?'case':'');sync();window.addEventListener('hashchange',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('popstate',sync)}},[project.id]);
 function change(value:string){setOpen(value);window.history.pushState(null,'',value?'#case-'+project.id:project.id==='coffee-shop'?'#work':'#additional-projects');window.dispatchEvent(new HashChangeEvent('hashchange'));}
 const optional=[['Findings',project.findings],['Dataset size',project.datasetSize],['Reporting period',project.reportingPeriod],['Dataset source',project.datasetSource],['KPI formulas',project.kpiFormulas],['Measured improvements',project.measuredImprovements]];
 return <div id={'case-'+project.id} className="case-study"><Accordion type="single" collapsible value={open} onValueChange={change}><AccordionItem value="case"><AccordionTrigger className="case-trigger">{open?'Close case study':'Explore case study'}</AccordionTrigger><AccordionContent className="case-content"><dl>{project.sections.map((section,index)=><div key={section.title}><dt>{section.title}</dt><dd>{section.text}</dd>{index===0&&<><dt>Tools</dt><dd>{project.tools.join(' · ')}</dd></>}</div>)}{optional.filter(([,v])=>v).map(([title,value])=><div key={title}><dt>{title}</dt><dd>{value}</dd></div>)}</dl>{project.screenshots?.length? <div className="screenshots">{project.screenshots.map(img=><img key={img.src} src={img.src} alt={img.alt} loading="lazy"/>)}</div>:null}</AccordionContent></AccordionItem></Accordion></div>;
}
function Socials(){return <div className="socials"><a href={'mailto:'+profile.contact.email}>Email <ArrowUpRight size={14}/></a><a href={profile.contact.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href={profile.contact.github} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={14}/></a></div>}
export default function Home(){
 const [menu,setMenu]=useState(false); const menuButton=useRef<HTMLButtonElement>(null);
 const [copy,setCopy]=useState<'idle'|'copied'|'failed'>('idle');
 useEffect(()=>{if(!menu)return;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);menuButton.current?.focus()}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[menu]);
 async function copyEmail(){try{await navigator.clipboard.writeText(profile.contact.email);setCopy('copied')}catch{setCopy('failed')}}
 const featured=projects[0];const practiceIcons=[ClipboardList,PackageSearch,Layers,Workflow];
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="site-header"><nav className="container nav" aria-label="Main navigation">
 <a href="#home" className="brand" aria-label={profile.name+' home'}><span className="brand-mark">MRU</span><span className="brand-copy"><strong>{profile.name}</strong><small>Data Analyst · Abu Dhabi</small></span></a>
 <button ref={menuButton} className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="main-nav" aria-label={menu?'Close navigation':'Open navigation'}>{menu?<X size={22}/>:<Menu size={22}/>}</button>
 <div id="main-nav" className={'nav-links'+(menu?' is-open':'')}>{navigation.map(([label,id])=><a className={id==='contact'?'nav-contact':''} key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}{profile.resume&&<a className="nav-resume" href={profile.resume} download>Resume <ArrowDown size={14}/></a>}</div>
 </nav></header>
 <main id="main"><div id="home" className="container"><section className="hero" aria-labelledby="hero-heading"><div className="hero-copy">
 <div className="hero-location"><span className="eyebrow">ANALYTICS · REPORTING · DECISION SUPPORT</span></div>
 <p className="professional-title">{profile.title}<span><MapPin size={13}/>{profile.location}</span></p>
 <h1 id="hero-heading">Turning sales and operational data into <em>clear business decisions.</em></h1>
 <p className="intro">{profile.introduction}</p>
 <div className="hero-actions"><a className="button" href="#work">View My Work <ArrowUpRight size={18}/></a>{profile.resume&&<a className="button secondary" href={profile.resume} download><FileText size={17}/>Download Resume</a>}</div>
 </div><aside className="profile-visual" aria-label="Professional profile"><div className="portrait-frame"><img src="./mohammed-ramees-ummer.webp" alt="Professional portrait of Mohammed Ramees Ummer" width="900" height="900"/><span className="portrait-status"><span className="status-dot" aria-hidden="true"/>Open to analytics roles</span></div><div className="portrait-caption"><div><strong>{profile.name}</strong><span>{profile.title}</span></div><p><MapPin size={14}/>{profile.location}</p></div></aside></section>
 <section className="hero-proof" aria-label="Resume-reported evidence"><div className="proof-heading"><p className="eyebrow">EVIDENCE FROM EXPERIENCE</p><span>Selected, resume-backed outcomes</span></div>{profile.evidence.map(e=><article key={e.value}><strong>{e.value}</strong><div><h2>{e.label}</h2><p>{e.source}</p></div></article>)}</section>
 <div className="availability"><p><span className="status-dot" aria-hidden="true"/>{profile.availability}</p><Socials/></div></div>
 <section className="container section featured" id="work" aria-labelledby="featured-title"><div className="section-heading"><div><p className="eyebrow">01 / FEATURED PROJECT</p><h2 id="featured-title">A business question.<br/>A clearer view.</h2></div><p>Retail sales analysis, from data<br className="desktop-break"/> preparation to business reporting.</p></div>
 <article className="featured-card"><div className="project-cover">{featured.screenshots?.length?<img src={featured.screenshots[0].src} alt={featured.screenshots[0].alt}/>:<><div className="cover-top"><span>SALES ANALYTICS</span><span>01</span></div><div className="cover-title">Coffee Shop<br/>Sales Dashboard<span className="cover-rule"/></div><div className="cover-bottom"><span>Excel / SQL / Power BI / DAX</span><span>PROJECT STUDY</span></div></>}</div>
 <div className="featured-info"><p className="eyebrow">{featured.category}</p><h3>{featured.title}</h3><p>{featured.summary}</p><Tags items={featured.tools}/><div className="project-deliverable"><span>THE DELIVERABLE</span><p>An interactive dashboard for sales performance and key business KPIs.</p></div><ProjectLinks project={featured}/></div>
 <div className="featured-study"><CaseStudy project={featured}/></div></article>
 </section>
 <section className="practice-section"><div className="container section" aria-labelledby="practice-title"><p className="eyebrow">02 / PROFESSIONAL ANALYTICS WORK</p><div className="section-heading"><h2 id="practice-title">Analytics work in practice.</h2><p>Responsibility-based summaries of my work<br className="desktop-break"/> at Vestano International.</p></div><div className="practice-grid">{profile.practice.map((item,i)=>{const Icon=practiceIcons[i];return <article key={item.title}><Icon size={23} strokeWidth={1.5}/><h3>{item.title}</h3><p>{item.text}</p></article>})}</div></div></section>
 <section className="container section" id="experience" aria-labelledby="experience-title"><p className="eyebrow">03 / EXPERIENCE</p><div className="section-heading"><h2 id="experience-title">Business focus.<br/>Technical foundation.</h2><p>Experience across retail analytics,<br className="desktop-break"/> data science, and software development.</p></div><div className="timeline">{profile.experience.map((job,i)=><article key={job.company} className={'job '+(i===0?'current-job':'')}><div className="job-period"><p>{job.dates}</p><span>{job.location}</span></div><div className="job-content"><p className="job-focus">{job.focus}</p><h3>{job.title}</h3><p className="company">{job.company}</p><ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</div></section>
 <section className="skills-section"><div className="container section" id="skills" aria-labelledby="skills-title"><p className="eyebrow">04 / SKILLS</p><h2 id="skills-title">The tools behind the analysis.</h2><div className="skills-grid">{profile.skills.map((group,i)=><article className={i===3?'supporting-skills':''} key={group.title}><span className="skill-number">0{i+1}</span><h3>{group.title}</h3><Tags items={group.items}/></article>)}</div><div className="secondary-skills"><span>Additional technical grounding</span><p>{profile.secondarySkills.join(' · ')}</p></div></div></section>
 <section className="container section" id="additional-projects" aria-labelledby="additional-title"><p className="eyebrow">05 / ADDITIONAL PROJECTS</p><div className="section-heading"><h2 id="additional-title">Beyond business reporting.</h2><p>Supporting projects in machine learning<br className="desktop-break"/> and computer vision.</p></div><div className="additional-grid">{projects.slice(1).map((project,i)=><article className="additional-card" key={project.id}><div className="project-card-top"><span>{project.category}</span><span>0{i+2}</span></div><h3>{project.title}</h3><p>{project.summary}</p><Tags items={project.tools}/>{project.result&&<p className="result-note">{project.result}</p>}<ProjectLinks project={project}/><CaseStudy project={project}/></article>)}</div></section>
 <section className="container section about" id="about" aria-labelledby="about-title"><div><p className="eyebrow">06 / ABOUT</p><h2 id="about-title">Connecting business context<br/>with technical understanding.</h2><p className="about-copy">{profile.about}</p></div><div className="credentials"><article><p className="eyebrow">EDUCATION</p><h3>{profile.education.degree}</h3><p>{profile.education.institution}</p><span>{profile.education.dates}</span></article><article><p className="eyebrow">CERTIFICATION</p><h3>{profile.certificate.title}</h3><p>{profile.certificate.date}</p>{profile.certificate.issuer&&<p>{profile.certificate.issuer}</p>}{profile.certificate.credentialId&&<p>{profile.certificate.credentialId}</p>}{profile.certificate.verificationUrl&&<a className="text-link" href={profile.certificate.verificationUrl} target="_blank" rel="noopener noreferrer">Verify certificate <ArrowUpRight size={15}/></a>}</article></div></section>
 <section className="contact-section" id="contact" aria-labelledby="contact-title"><div className="container contact"><div><p className="eyebrow">07 / CONTACT</p><h2 id="contact-title">{profile.contactHeading}</h2><p>{profile.contactText}</p><span className="contact-location"><MapPin size={16}/>{profile.location}</span></div><div className="contact-methods"><a className="email-link" href={'mailto:'+profile.contact.email}>{profile.contact.email}<ArrowUpRight size={25}/></a><button className="copy-button" onClick={copyEmail}>{copy==='copied'?<Check size={15}/>:<Copy size={15}/>} {copy==='copied'?'Email copied':'Copy email'}</button><p className="copy-feedback" role="status">{copy==='failed'?'Copy unavailable. Select the email address above to copy it, or open your email app.':copy==='copied'?'Email address copied to clipboard.':''}</p><Socials/>{profile.contact.showPhone&&<a href={'tel:'+profile.contact.phone.replace(/\s/g,'')}>{profile.contact.phone}</a>}{profile.resume&&<a className="resume-contact" href={profile.resume} download>Download Resume <ArrowDown size={15}/></a>}</div></div></section>
 </main><footer className="container footer"><a href="#home" className="brand">MRU</a><p>{profile.name}<span>Data Analyst | Business &amp; MIS Reporting</span></p><a href="#home">Back to top ↑</a></footer>
 </>;
}

